version: "3.4"

networks:
    frontend:
    backend:

services:
    event:
        build:
            context: .\EventCatalogAPI
            dockerfile: Dockerfile
        image: event/catalogapi
        environment:
            DatabaseServer: mssqlserver
            DatabaseName: EventDb
            DatabaseUser: sa
            DatabaseUserPassword: EventApi(!)
            ExternalCatalogBaseUrl: http://localhost:5510
        container_name: eventapi
        ports:
            - "5510:80"
        networks:
            - backend
            - frontend
        depends_on:
            - mssqlserver

    webmvc:
        build:
            context: .\WebMvc
            dockerfile: Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: Development 
            CatalogUrl: http://event
            #please change the first part to your own IP address
            IdentityUrl: http://192.168.1.132:7000
            CallBackRul: http://localhost:6200
        container_name: eventshop
        ports:
            - "6200:80"
        networks:
            - frontend 
        depends_on:
            - event
            - tokenserver

    tokenserver:
        build:
            context: .\TokenServiceApi
            dockerfile: Dockerfile
        environment:
            DASPNETCORE_ENVIRONMENT: Development
            MvcClient: http://localhost:6200
        container_name: tokenserviceapi
        ports:
            - "7000:80"
        networks:
            - backend
            - frontend
        depends_on:
            - mssqlserver

    mssqlserver:
        image: "microsoft/mssql-server-linux:latest"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: EventApi(!)
        container_name: eventserver
        ports:
            - "1450:1433"
        networks:
            - backend
